# /docker-compose.yml
version: '3.9'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    hostname: "localhost"
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      - TZ=Europe/Moscow
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

  # adblock:
  #   build: ./adblock
  #   ports:
  #     - "8118:8118"
